name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pillow
        
    - name: Create application icon
      run: python create_icon.py
      
    - name: Build executable
      run: python build.py
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lexia-windows
        path: |
          dist/Lexia.exe
          release/
          Lexia-v*.zip
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          Lexia-v*.zip
          dist/Lexia.exe
        body: |
          ## 🎉 Lexia Release ${{ github.ref_name }}
          
          ### ✨ What's New
          - **GUI-based API Key Management** - No more config.py editing!
          - **First-time Setup Wizard** - Automatic setup on first run
          - **Professional Settings UI** - Tabbed interface with secure key storage
          - **Zero-Setup Experience** - Download → Run → Enter Keys → Done!
          - **Improved User Experience** - Perfect for mainstream distribution
          
          ### 📦 Installation (Super Easy!)
          1. Download `Lexia-${{ github.ref_name }}-Windows.zip`
          2. Extract to any folder
          3. Run `Lexia.exe`
          4. Enter your API keys in the setup wizard
          5. Start rewriting text with `Ctrl+Shift+R`!
          
          ### 🔧 Requirements
          - Windows 10/11
          - OpenAI API Key and/or Groq API Key (entered through GUI)
          - Internet connection for AI processing
          
          ### 🚀 Features
          - **Global Hotkey**: Works across all applications
          - **Multiple AI Models**: GPT-4 (OpenAI) + Llama-4-Scout (Groq)
          - **6 Preset Styles** + Custom instructions
          - **3 Alternative Rewrites** per request
          - **Professional About Dialog** with update checking
          
          **Made with ❤️ by Muhammad Jawad Bashir**
          
          **Full Changelog**: https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-info:
    runs-on: ubuntu-latest
    steps:
    - name: Show build info
      run: |
        echo "🚀 Building Lexia release"
        echo "📅 Date: $(date)"
        echo "🏷️  Tag: ${{ github.ref_name }}"
        echo "📝 Commit: ${{ github.sha }}"